apiVersion: v1
kind: Service
metadata:
  name: '${SERVICE_WEB@microservice-home-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    moduleid: microservice-home-web-service
    version: 1.70.0-auth-config-info
spec:
  type: NodePort
  selector:
    app: '${DEPLOYMENT_WEB@microservice-home-config}'
  ports:
    -
      name: microservice-home-web-port
      port: '${INTERNAL_PORT_APP@microservice-home-config}'
